# ----------------------------
# Makefile Options
# ----------------------------

NAME = QFEIMP
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
